### ISSUE TITLE
Button wrapping issue on re-size

### ISSUE THREAD

**Issue by mandiwise** [redacademy/rise-summer-2016#1]
Noticed this when adjusting the window width back and forth:

<img width="327" alt="button-issue" src="https://cloud.githubusercontent.com/assets/1518780/18560862/470d22f8-7b32-11e6-98ed-f2f973f473ff.png">

Be sure to allow enough room for the button at all applicable screen widths.

**Comment by teeppope** [comment]
I have prevented the button from wrapping while scaling down, but now it just overlaps the nav

**Comment by Joseph-Lam** [comment]
fixed button wrapping
