### ISSUE TITLE
Enqueue all scripts and styles in funcitons.php

### ISSUE THREAD

**Issue by mandiwise** [redacademy/rise-summer-2016#5]
The following scripts need to be removed from header.php and properly enqueued in funcitons.php:
- jQuery (and only enqueue it once...you have two different versions in header.php)
- hamburger-menu.js (and add jQuery as a dependency)

Also, don't use `bloginfo("template_url")` when generating the theme path to these scripts (use `get_template_directory_uri()`).

**Comment by teeppope** [comment]
I have removed script tags from header.php, enqueued them properly in functions.php and removed the extra version of jquery.

**Comment by teeppope** [comment]
I have added jquery as a dependency and enqueued the dependancy's jquery.min.js file in functions.php
