### ISSUE TITLE
Use template parts where content will be re-used

### ISSUE THREAD

**Issue by mandiwise** [redacademy/rise-summer-2016#8]
Re-consider some of your use of template parts, for example, will content-students.php be used anywhere but the page-students.php template? If not, then simply placing this php/mark-up directly in page-students.php would be fine.

**Comment by teeppope** [comment]
I have moved the content-about into the page-about-us.php

**Comment by Joseph-Lam** [comment]
I have moved the content templates for contact, donate, and students pages and put them into their respective page-contact, page-donate, and page-students .php files. I have also reformatted the code to be more semantic using sections and lists.
